
const ListingPageConstant = {
  SEARCH:"LISTING_PAGE_CONSTANT_SEARCH",
  LOADING_PRODUCT:"LISTING_PAGE_CONSTANT_LOADING_PRODUCT",
  LOADING_BRAND:"LISTING_PAGE_CONSTANT_LOADING_BRAND",
  DONE_LOADING_PRODUCT:"LISTING_PAGE_CONSTANT_DONE_LOADING_PRODUCT",
  DONE_LOADING_BRAND:"LISTING_PAGE_CONSTANT_DONE_LOADING_BRAND",
  ADD_BRAND_TO_LIST:"LISTING_PAGE_CONSTANT_ADD_BRAND_TO_LIST",
  CHECK_BRAND:"LISTING_PAGE_CONSTANT_CHECK_BRAND",
  SEARCH_BRAND:"LISTING_PAGE_CONSTANT_SEARCH_BRAND",
  UPDATE_PRODUCT_LIST:"LISTING_PAGE_CONSTANT_UPDATE_PRODUCT_LIST",
  ADD_PRODUCT_TO_LIST:"LISTING_PAGE_CONSTANT_ADD_PRODUCT_TO_LIST",
  CLEAR_PRODUCT:"LISTING_PAGE_CONSTANT_CLEAR_PRODUCT",
  CHANGE_PAGE:"LISTING_PAGE_CONSTANT_CHANGE_PAGE",
  LOAD_PRODUCT_TO_LIST:"LISTING_PAGE_CONSTANT_LOAD_PRODUCT_TO_LIST",
  SEARCH_CHANGE:"LISTING_PAGE_CONSTANT_SEARCH_CHANGE",
  HIDE_SEARCH:"LISTING_PAGE_CONSTANT_HIDE_SEARCH",
  GET_AFFILIATE:"LISTING_PAGE_CONSTANT_GET_AFFILIATE"
}

export default ListingPageConstant