
const NewsletterConstant = {
  SUBMIT:"NEWSLETTER_CONSTANT_SUBMIT",
  SUCCESS_SUBMIT:"NEWSLETTER_CONSTANT_SUCCESS_SUBMIT",
  CHANGE_FIELD:"NEWSLETTER_CONSTANT_CHANGE_FIELD",
  FORMERROR:"NEWSLETTER_CONSTANT_FORM_ERROR",
  LOADING_FORM:"NEWSLETTER_CONSTANT_LOADING_PRODUCT"
}

export default NewsletterConstant