
const ProductSingleConstant = {
  LOADING_PRODUCT:"SINGLE_PRODUCT_CONSTANT_LOADING_PRODUCT",
  DONE_LOADING_PRODUCT:"SINGLE_PRODUCT_CONSTANT_DONE_LOADING_PRODUCT",
  GET_AFFILIATE:"SINGLE_PRODUCT_CONSTANT_DONE_GET_AFFILIATE"
}

export default ProductSingleConstant