const SearchFormConstant = {
  SUBMIT_FORM:"HOME_SEARCH_FORM_SUBMIT",
  CHANGE_CATEGORY:"HOME_SEARCH_CHANGE_CATEGORY",
  CHANGE_TYPE:"HOME_SEARCH_CHANGE_TYPE",
  CHANGE_BRAND:"HOME_SEARCH_CHANGE_BRAND",
  ADD_BRAND_TO_LIST:"HOME_SEARCH_ADD_BRAND_TO_LIST",
  SEARCH_TEXT:"HOME_SEARCH_SEARCH_TEXT",
  SUBMIT_FORM_ERROR:"HOME_SEARCH_SUBMIT_FORM_ERROR",
  NOTHING:"NOTHING"
}

export default SearchFormConstant
